// Code generated by ZEBRAPACK (github.com/glycerine/zebrapack). DO NOT EDIT.

package gdax

import (
	"github.com/glycerine/zebrapack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *Channel) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields1zgensym_fbe4305ea49d48fc_2 = 3

	// -- templateDecodeMsgZid starts here--
	var totalEncodedFields1zgensym_fbe4305ea49d48fc_2 uint32
	totalEncodedFields1zgensym_fbe4305ea49d48fc_2, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft1zgensym_fbe4305ea49d48fc_2 := totalEncodedFields1zgensym_fbe4305ea49d48fc_2
	missingFieldsLeft1zgensym_fbe4305ea49d48fc_2 := maxFields1zgensym_fbe4305ea49d48fc_2 - totalEncodedFields1zgensym_fbe4305ea49d48fc_2

	var nextMiss1zgensym_fbe4305ea49d48fc_2 int = -1
	var found1zgensym_fbe4305ea49d48fc_2 [maxFields1zgensym_fbe4305ea49d48fc_2]bool
	var curField1zgensym_fbe4305ea49d48fc_2 int

doneWithStruct1zgensym_fbe4305ea49d48fc_2:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft1zgensym_fbe4305ea49d48fc_2 > 0 || missingFieldsLeft1zgensym_fbe4305ea49d48fc_2 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft1zgensym_fbe4305ea49d48fc_2, missingFieldsLeft1zgensym_fbe4305ea49d48fc_2, msgp.ShowFound(found1zgensym_fbe4305ea49d48fc_2[:]), decodeMsgFieldOrder1zgensym_fbe4305ea49d48fc_2)
		if encodedFieldsLeft1zgensym_fbe4305ea49d48fc_2 > 0 {
			encodedFieldsLeft1zgensym_fbe4305ea49d48fc_2--
			curField1zgensym_fbe4305ea49d48fc_2, err = dc.ReadInt()
			if err != nil {
				return
			}
		} else {
			//missing fields need handling
			if nextMiss1zgensym_fbe4305ea49d48fc_2 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss1zgensym_fbe4305ea49d48fc_2 = 0
			}
			for nextMiss1zgensym_fbe4305ea49d48fc_2 < maxFields1zgensym_fbe4305ea49d48fc_2 && (found1zgensym_fbe4305ea49d48fc_2[nextMiss1zgensym_fbe4305ea49d48fc_2] || decodeMsgFieldSkip1zgensym_fbe4305ea49d48fc_2[nextMiss1zgensym_fbe4305ea49d48fc_2]) {
				nextMiss1zgensym_fbe4305ea49d48fc_2++
			}
			if nextMiss1zgensym_fbe4305ea49d48fc_2 == maxFields1zgensym_fbe4305ea49d48fc_2 {
				// filled all the empty fields!
				break doneWithStruct1zgensym_fbe4305ea49d48fc_2
			}
			missingFieldsLeft1zgensym_fbe4305ea49d48fc_2--
			curField1zgensym_fbe4305ea49d48fc_2 = nextMiss1zgensym_fbe4305ea49d48fc_2
		}
		//fmt.Printf("switching on curField: '%v'\n", curField1zgensym_fbe4305ea49d48fc_2)
		switch curField1zgensym_fbe4305ea49d48fc_2 {
		// -- templateDecodeMsgZid ends here --

		case 0:
			// zid 0 for "BaseMsg"
			found1zgensym_fbe4305ea49d48fc_2[0] = true
			err = z.BaseMsg.DecodeMsg(dc)
			if err != nil {
				return
			}
		case 1:
			// zid 1 for "Name"
			found1zgensym_fbe4305ea49d48fc_2[1] = true
			z.Name, err = dc.ReadString()
			if err != nil {
				return
			}
		case 2:
			// zid 2 for "ProductIDs"
			found1zgensym_fbe4305ea49d48fc_2[2] = true
			var zgensym_fbe4305ea49d48fc_3 uint32
			zgensym_fbe4305ea49d48fc_3, err = dc.ReadArrayHeader()
			if err != nil {
				return
			}
			if cap(z.ProductIDs) >= int(zgensym_fbe4305ea49d48fc_3) {
				z.ProductIDs = (z.ProductIDs)[:zgensym_fbe4305ea49d48fc_3]
			} else {
				z.ProductIDs = make([]string, zgensym_fbe4305ea49d48fc_3)
			}
			for zgensym_fbe4305ea49d48fc_0 := range z.ProductIDs {
				z.ProductIDs[zgensym_fbe4305ea49d48fc_0], err = dc.ReadString()
				if err != nil {
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss1zgensym_fbe4305ea49d48fc_2 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Channel
var decodeMsgFieldOrder1zgensym_fbe4305ea49d48fc_2 = []string{"BaseMsg", "Name", "ProductIDs"}

var decodeMsgFieldSkip1zgensym_fbe4305ea49d48fc_2 = []bool{false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *Channel) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 3
	}
	var fieldsInUse uint32 = 3
	isempty[0] = false
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.Name) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (len(z.ProductIDs) == 0) // string, omitempty
	if isempty[2] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *Channel) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_fbe4305ea49d48fc_4 [3]bool
	fieldsInUse_zgensym_fbe4305ea49d48fc_5 := z.fieldsNotEmpty(empty_zgensym_fbe4305ea49d48fc_4[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_fbe4305ea49d48fc_5)
	if err != nil {
		return err
	}

	if !empty_zgensym_fbe4305ea49d48fc_4[0] {
		// zid 0 for "BaseMsg"
		err = en.Append(0x0)
		if err != nil {
			return err
		}
		err = z.BaseMsg.EncodeMsg(en)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_fbe4305ea49d48fc_4[1] {
		// zid 1 for "Name"
		err = en.Append(0x1)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Name)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_fbe4305ea49d48fc_4[2] {
		// zid 2 for "ProductIDs"
		err = en.Append(0x2)
		if err != nil {
			return err
		}
		err = en.WriteArrayHeader(uint32(len(z.ProductIDs)))
		if err != nil {
			return
		}
		for zgensym_fbe4305ea49d48fc_0 := range z.ProductIDs {
			err = en.WriteString(z.ProductIDs[zgensym_fbe4305ea49d48fc_0])
			if err != nil {
				return
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Channel) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [3]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// zid 0 for "BaseMsg"
		o = append(o, 0x0)
		o, err = z.BaseMsg.MarshalMsg(o) // not is.iface, gen/marshal.go:261
		if err != nil {
			return
		}
	}

	if !empty[1] {
		// zid 1 for "Name"
		o = append(o, 0x1)
		o = msgp.AppendString(o, z.Name)
	}

	if !empty[2] {
		// zid 2 for "ProductIDs"
		o = append(o, 0x2)
		o = msgp.AppendArrayHeader(o, uint32(len(z.ProductIDs)))
		for zgensym_fbe4305ea49d48fc_0 := range z.ProductIDs {
			o = msgp.AppendString(o, z.ProductIDs[zgensym_fbe4305ea49d48fc_0])
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Channel) UnmarshalMsg(bts []byte) (o []byte, err error) {
	cfg := &msgp.RuntimeConfig{UnsafeZeroCopy: true}
	return z.UnmarshalMsgWithCfg(bts, cfg)
}
func (z *Channel) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields6zgensym_fbe4305ea49d48fc_7 = 3

	// -- templateUnmarshalMsgZid starts here--
	var totalEncodedFields6zgensym_fbe4305ea49d48fc_7 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields6zgensym_fbe4305ea49d48fc_7, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft6zgensym_fbe4305ea49d48fc_7 := totalEncodedFields6zgensym_fbe4305ea49d48fc_7
	missingFieldsLeft6zgensym_fbe4305ea49d48fc_7 := maxFields6zgensym_fbe4305ea49d48fc_7 - totalEncodedFields6zgensym_fbe4305ea49d48fc_7

	var nextMiss6zgensym_fbe4305ea49d48fc_7 int = -1
	var found6zgensym_fbe4305ea49d48fc_7 [maxFields6zgensym_fbe4305ea49d48fc_7]bool
	var curField6zgensym_fbe4305ea49d48fc_7 int

doneWithStruct6zgensym_fbe4305ea49d48fc_7:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft6zgensym_fbe4305ea49d48fc_7 > 0 || missingFieldsLeft6zgensym_fbe4305ea49d48fc_7 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft6zgensym_fbe4305ea49d48fc_7, missingFieldsLeft6zgensym_fbe4305ea49d48fc_7, msgp.ShowFound(found6zgensym_fbe4305ea49d48fc_7[:]), unmarshalMsgFieldOrder6zgensym_fbe4305ea49d48fc_7)
		if encodedFieldsLeft6zgensym_fbe4305ea49d48fc_7 > 0 {
			encodedFieldsLeft6zgensym_fbe4305ea49d48fc_7--
			curField6zgensym_fbe4305ea49d48fc_7, bts, err = nbs.ReadIntBytes(bts)
			if err != nil {
				return
			}
		} else {
			//missing fields need handling
			if nextMiss6zgensym_fbe4305ea49d48fc_7 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss6zgensym_fbe4305ea49d48fc_7 = 0
			}
			for nextMiss6zgensym_fbe4305ea49d48fc_7 < maxFields6zgensym_fbe4305ea49d48fc_7 && (found6zgensym_fbe4305ea49d48fc_7[nextMiss6zgensym_fbe4305ea49d48fc_7] || unmarshalMsgFieldSkip6zgensym_fbe4305ea49d48fc_7[nextMiss6zgensym_fbe4305ea49d48fc_7]) {
				nextMiss6zgensym_fbe4305ea49d48fc_7++
			}
			if nextMiss6zgensym_fbe4305ea49d48fc_7 == maxFields6zgensym_fbe4305ea49d48fc_7 {
				// filled all the empty fields!
				break doneWithStruct6zgensym_fbe4305ea49d48fc_7
			}
			missingFieldsLeft6zgensym_fbe4305ea49d48fc_7--
			curField6zgensym_fbe4305ea49d48fc_7 = nextMiss6zgensym_fbe4305ea49d48fc_7
		}
		//fmt.Printf("switching on curField: '%v'\n", curField6zgensym_fbe4305ea49d48fc_7)
		switch curField6zgensym_fbe4305ea49d48fc_7 {
		// -- templateUnmarshalMsgZid ends here --

		case 0:
			// zid 0 for "BaseMsg"
			found6zgensym_fbe4305ea49d48fc_7[0] = true
			bts, err = z.BaseMsg.UnmarshalMsg(bts)
			if err != nil {
				return
			}
		case 1:
			// zid 1 for "Name"
			found6zgensym_fbe4305ea49d48fc_7[1] = true
			z.Name, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case 2:
			// zid 2 for "ProductIDs"
			found6zgensym_fbe4305ea49d48fc_7[2] = true
			if nbs.AlwaysNil {
				(z.ProductIDs) = (z.ProductIDs)[:0]
			} else {

				var zgensym_fbe4305ea49d48fc_8 uint32
				zgensym_fbe4305ea49d48fc_8, bts, err = nbs.ReadArrayHeaderBytes(bts)
				if err != nil {
					return
				}
				if cap(z.ProductIDs) >= int(zgensym_fbe4305ea49d48fc_8) {
					z.ProductIDs = (z.ProductIDs)[:zgensym_fbe4305ea49d48fc_8]
				} else {
					z.ProductIDs = make([]string, zgensym_fbe4305ea49d48fc_8)
				}
				for zgensym_fbe4305ea49d48fc_0 := range z.ProductIDs {
					z.ProductIDs[zgensym_fbe4305ea49d48fc_0], bts, err = nbs.ReadStringBytes(bts)

					if err != nil {
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss6zgensym_fbe4305ea49d48fc_7 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Channel
var unmarshalMsgFieldOrder6zgensym_fbe4305ea49d48fc_7 = []string{"BaseMsg", "Name", "ProductIDs"}

var unmarshalMsgFieldSkip6zgensym_fbe4305ea49d48fc_7 = []bool{false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Channel) Msgsize() (s int) {
	s = 1 + 8 + z.BaseMsg.Msgsize() + 5 + msgp.StringPrefixSize + len(z.Name) + 11 + msgp.ArrayHeaderSize
	for zgensym_fbe4305ea49d48fc_0 := range z.ProductIDs {
		s += msgp.StringPrefixSize + len(z.ProductIDs[zgensym_fbe4305ea49d48fc_0])
	}
	return
}

// FileChannel holds ZebraPack schema from file 'channel.go'
type FileChannel struct{}

// ZebraSchemaInMsgpack2Format provides the ZebraPack Schema in msgpack2 format, length 544 bytes
func (FileChannel) ZebraSchemaInMsgpack2Format() []byte {
	return []byte{
		0x84, 0xaa, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61,
		0x74, 0x68, 0xaa, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
		0x2e, 0x67, 0x6f, 0xad, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
		0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0xa4, 0x67, 0x64,
		0x61, 0x78, 0xa7, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73,
		0x81, 0xa7, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x82,
		0xaa, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d,
		0x65, 0xa7, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0xa6,
		0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x93, 0x87, 0xa3, 0x5a,
		0x69, 0x64, 0x00, 0xab, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x47,
		0x6f, 0x4e, 0x61, 0x6d, 0x65, 0xa7, 0x42, 0x61, 0x73, 0x65,
		0x4d, 0x73, 0x67, 0xac, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54,
		0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0xa7, 0x42, 0x61, 0x73,
		0x65, 0x4d, 0x73, 0x67, 0xac, 0x46, 0x69, 0x65, 0x6c, 0x64,
		0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x72, 0xaa, 0x62, 0x6d,
		0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x73, 0x67, 0xad, 0x46,
		0x69, 0x65, 0x6c, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
		0x72, 0x79, 0x17, 0xae, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50,
		0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x16, 0xad,
		0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x75, 0x6c, 0x6c, 0x54,
		0x79, 0x70, 0x65, 0x82, 0xa4, 0x4b, 0x69, 0x6e, 0x64, 0x16,
		0xa3, 0x53, 0x74, 0x72, 0xaa, 0x62, 0x6d, 0x2e, 0x42, 0x61,
		0x73, 0x65, 0x4d, 0x73, 0x67, 0x87, 0xa3, 0x5a, 0x69, 0x64,
		0x01, 0xab, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x47, 0x6f, 0x4e,
		0x61, 0x6d, 0x65, 0xa4, 0x4e, 0x61, 0x6d, 0x65, 0xac, 0x46,
		0x69, 0x65, 0x6c, 0x64, 0x54, 0x61, 0x67, 0x4e, 0x61, 0x6d,
		0x65, 0xa4, 0x4e, 0x61, 0x6d, 0x65, 0xac, 0x46, 0x69, 0x65,
		0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x72, 0xa6,
		0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0xad, 0x46, 0x69, 0x65,
		0x6c, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
		0x17, 0xae, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x72, 0x69,
		0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x02, 0xad, 0x46, 0x69,
		0x65, 0x6c, 0x64, 0x46, 0x75, 0x6c, 0x6c, 0x54, 0x79, 0x70,
		0x65, 0x82, 0xa4, 0x4b, 0x69, 0x6e, 0x64, 0x02, 0xa3, 0x53,
		0x74, 0x72, 0xa6, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x86,
		0xa3, 0x5a, 0x69, 0x64, 0x02, 0xab, 0x46, 0x69, 0x65, 0x6c,
		0x64, 0x47, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0xaa, 0x50, 0x72,
		0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0xac, 0x46,
		0x69, 0x65, 0x6c, 0x64, 0x54, 0x61, 0x67, 0x4e, 0x61, 0x6d,
		0x65, 0xaa, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
		0x44, 0x73, 0xac, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79,
		0x70, 0x65, 0x53, 0x74, 0x72, 0xa8, 0x5b, 0x5d, 0x73, 0x74,
		0x72, 0x69, 0x6e, 0x67, 0xad, 0x46, 0x69, 0x65, 0x6c, 0x64,
		0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x1a, 0xad,
		0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x75, 0x6c, 0x6c, 0x54,
		0x79, 0x70, 0x65, 0x83, 0xa4, 0x4b, 0x69, 0x6e, 0x64, 0x1a,
		0xa3, 0x53, 0x74, 0x72, 0xa5, 0x53, 0x6c, 0x69, 0x63, 0x65,
		0xa6, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x82, 0xa4, 0x4b,
		0x69, 0x6e, 0x64, 0x02, 0xa3, 0x53, 0x74, 0x72, 0xa6, 0x73,
		0x74, 0x72, 0x69, 0x6e, 0x67, 0xa7, 0x49, 0x6d, 0x70, 0x6f,
		0x72, 0x74, 0x73, 0x91, 0xd9, 0x26, 0x62, 0x6d, 0x20, 0x22,
		0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
		0x2f, 0x70, 0x72, 0x6f, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x61,
		0x62, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x61, 0x73, 0x65,
		0x6d, 0x73, 0x67, 0x22,
	}
}

// ZebraSchemaInJsonCompact provides the ZebraPack Schema in compact JSON format, length 680 bytes
func (FileChannel) ZebraSchemaInJsonCompact() []byte {
	return []byte(`{"SourcePath":"channel.go","SourcePackage":"gdax","Structs":{"Channel":{"StructName":"Channel","Fields":[{"Zid":0,"FieldGoName":"BaseMsg","FieldTagName":"BaseMsg","FieldTypeStr":"bm.BaseMsg","FieldCategory":23,"FieldPrimitive":22,"FieldFullType":{"Kind":22,"Str":"bm.BaseMsg"}},{"Zid":1,"FieldGoName":"Name","FieldTagName":"Name","FieldTypeStr":"string","FieldCategory":23,"FieldPrimitive":2,"FieldFullType":{"Kind":2,"Str":"string"}},{"Zid":2,"FieldGoName":"ProductIDs","FieldTagName":"ProductIDs","FieldTypeStr":"[]string","FieldCategory":26,"FieldFullType":{"Kind":26,"Str":"Slice","Domain":{"Kind":2,"Str":"string"}}}]}},"Imports":["bm \"github.com/prodatalab/msg/basemsg\""]}`)
}

// ZebraSchemaInJsonPretty provides the ZebraPack Schema in pretty JSON format, length 1656 bytes
func (FileChannel) ZebraSchemaInJsonPretty() []byte {
	return []byte(`{
    "SourcePath": "channel.go",
    "SourcePackage": "gdax",
    "Structs": {
        "Channel": {
            "StructName": "Channel",
            "Fields": [
                {
                    "Zid": 0,
                    "FieldGoName": "BaseMsg",
                    "FieldTagName": "BaseMsg",
                    "FieldTypeStr": "bm.BaseMsg",
                    "FieldCategory": 23,
                    "FieldPrimitive": 22,
                    "FieldFullType": {
                        "Kind": 22,
                        "Str": "bm.BaseMsg"
                    }
                },
                {
                    "Zid": 1,
                    "FieldGoName": "Name",
                    "FieldTagName": "Name",
                    "FieldTypeStr": "string",
                    "FieldCategory": 23,
                    "FieldPrimitive": 2,
                    "FieldFullType": {
                        "Kind": 2,
                        "Str": "string"
                    }
                },
                {
                    "Zid": 2,
                    "FieldGoName": "ProductIDs",
                    "FieldTagName": "ProductIDs",
                    "FieldTypeStr": "[]string",
                    "FieldCategory": 26,
                    "FieldFullType": {
                        "Kind": 26,
                        "Str": "Slice",
                        "Domain": {
                            "Kind": 2,
                            "Str": "string"
                        }
                    }
                }
            ]
        }
    },
    "Imports": [
        "bm \"github.com/prodatalab/msg/basemsg\""
    ]
}`)
}
